# This is a basic workflow to help you get started with Actions

name: Update Library

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: 1. Set-up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.17

      - name: 2. Install dependencies
        run: npm i

      - name: 3. Install dependencies
        run: npm i

      - name: 4. Run build
        run: npm run build

      - name: 5. Semantic release
        env:
          GH_TOKEN: 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
          NPM_TOKEN: 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
        run: npx semantic-release
